formatter: "markdown table"

sections:
  show: 
    - requirements
    - inputs 
    - outputs

output:
  file: README.md
  mode: inject
  template: |
    <!-- BEGIN_TF_DOCS -->
    '{{ .Content }}'
    "{{ .Content }}"
    <!-- END_TF_DOCS -->

settings:
  hide-empty: true