# https://terraform-docs.io/user-guide/configuration/

formatter: "markdown table"

sections:
  show: 
    - requirements
    - data-sources
    - inputs 
    - outputs

output:
  file: README.md

settings:
  hide-empty: true